### ISSUE TITLE
When using with Stitch, specific pairings of tables will throw "name...is not defined" error

### ISSUE THREAD

**Issue by allenjhyang** [singer-io/tap-zoom#7]
We're using this tap via Stitch. It was working at least up to a couple weeks ago, but recently has been erroring out with `name 'details' is not defined`

What I've noticed is that if I try to extract both `report_meeting_participants` and `meetings` in the same extraction, it'll throw this error. But if I do one or the other, it'll work fine.

The relevant part of the logs:

> 2020-11-05 17:33:17,332Z    tap - CRITICAL name 'details' is not defined
> 2020-11-05 17:33:17,332Z    tap - Traceback (most recent call last):
> 2020-11-05 17:33:17,332Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff/_sync.py", line 94, in retry
> 2020-11-05 17:33:17,332Z    tap -     ret = target(*args, **kwargs)
> 2020-11-05 17:33:17,332Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/ratelimit/decorators.py", line 77, in wrapper
> 2020-11-05 17:33:17,332Z    tap -     raise RateLimitException('too many calls', period_remaining)
> 2020-11-05 17:33:17,332Z    tap - ratelimit.exception.RateLimitException: too many calls
> 2020-11-05 17:33:17,332Z    tap - 
> 2020-11-05 17:33:17,332Z    tap - During handling of the above exception, another exception occurred:
> 2020-11-05 17:33:17,332Z    tap - 
> 2020-11-05 17:33:17,332Z    tap - Traceback (most recent call last):
> 2020-11-05 17:33:17,332Z    tap -   File "tap-env/bin/tap-zoom", line 33, in <module>
> 2020-11-05 17:33:17,332Z    tap -     sys.exit(load_entry_point('tap-zoom==0.0.2', 'console_scripts', 'tap-zoom')())
> 2020-11-05 17:33:17,332Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/singer/utils.py", line 229, in wrapped
> 2020-11-05 17:33:17,332Z    tap -     return fnc(*args, **kwargs)
> 2020-11-05 17:33:17,332Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zoom/__init__.py", line 41, in main
> 2020-11-05 17:33:17,333Z    tap -     parsed_args.state)
> 2020-11-05 17:33:17,333Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zoom/sync.py", line 138, in sync
> 2020-11-05 17:33:17,333Z    tap -     {})
> 2020-11-05 17:33:17,333Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zoom/sync.py", line 89, in sync_endpoint
> 2020-11-05 17:33:17,333Z    tap -     child_key_bag)
> 2020-11-05 17:33:17,333Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zoom/sync.py", line 89, in sync_endpoint
> 2020-11-05 17:33:17,333Z    tap -     child_key_bag)
> 2020-11-05 17:33:17,333Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zoom/sync.py", line 55, in sync_endpoint
> 2020-11-05 17:33:17,333Z    tap -     ignore_http_error_codes=endpoint.get('ignore_http_error_codes', []))
> 2020-11-05 17:33:17,333Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zoom/client.py", line 130, in get
> 2020-11-05 17:33:17,333Z    tap -     return self.request('GET', path=path, **kwargs)
> 2020-11-05 17:33:17,333Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff/_sync.py", line 110, in retry
> 2020-11-05 17:33:17,333Z    tap -     _call_handlers(on_backoff, *details, wait=seconds)
> 2020-11-05 17:33:17,333Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/backoff/_sync.py", line 20, in _call_handlers
> 2020-11-05 17:33:17,333Z    tap -     hdlr(details)
> 2020-11-05 17:33:17,333Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_zoom/client.py", line 21, in log_backoff_attempt
> 2020-11-05 17:33:17,333Z    tap -     details.get("tries"))
> 2020-11-05 17:33:17,333Z    tap - NameError: name 'details' is not defined
> 2020-11-05 17:33:17,335Z target - INFO Requests complete, stopping loop
> 2020-11-05 17:33:17,380Z   main - INFO Target exited normally with status 0
> 2020-11-05 17:33:17,926Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [6] at offset None
> 2020-11-05 17:33:17,927Z   main - INFO No tunnel subprocess to tear down
> 2020-11-05 17:33:17,927Z   main - INFO Exit status is: Discovery succeeded. Tap failed with code 1 and error message: "name 'details' is not defined". Target succeeded.

**Comment by allenjhyang** [comment]
This may be solved with #4 (and the error message is a red herring, but is solved with #8)

**Comment by rdeshmukh15** [comment]
@ajyang818 : If the issue is resolved, Can I close this issue? Please confirm
